import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Part 1: Fundamentals of Robotics',
      items: [
        'part1-fundamentals-of-robotics/kinematics',
        'part1-fundamentals-of-robotics/dynamics',
        'part1-fundamentals-of-robotics/control-systems',
      ],
    },
    {
      type: 'category',
      label: 'Part 2: AI for Robotics',
      items: [
        'part2-ai-for-robotics/planning',
        'part2-ai-for-robotics/perception',
        'part2-ai-for-robotics/learning',
      ],
    },
    {
      type: 'category',
      label: 'Part 3: Humanoid Robotics',
      items: [
        'part3-humanoid-robotics/bipedal-locomotion',
        'part3-humanoid-robotics/manipulation',
        'part3-humanoid-robotics/human-robot-interaction',
      ],
    },
    {
      type: 'category',
      label: 'Tutorial Basics',
      items: ['tutorial-basics/create-a-blog-post'],
    },
  ],
};

export default sidebars;
